import 'package:flutter/material.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedGroup115Widget.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedUser1Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedAlina01Widget.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/Generated30Widget.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedGroup34Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedIPhoneX11ProLightBaseWidget3.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedVector6Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedEllipse12Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedRectangle20Widget13.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedWpffaqWidget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedEllipse10Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedCombinedShapeWidget3.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedGroup90Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedEllipse11Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedUserpicWidget.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedHomeIndicatorWidget2.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedGroup116Widget.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedNotificationWidget1.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedEllipse11Widget2.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedGroup112Widget.dart';
import 'package:flutterapp/meckathonapp/generatedactualitewidget/generated/GeneratedEllipse12Widget2.dart';

/* Frame Actualite
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedActualiteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1456.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1456.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 233, 233, 233),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 36.776119232177734,
                              child: GeneratedIPhoneX11ProLightBaseWidget3(),
                            ),
                            Positioned(
                              left: -536.5,
                              top: 395.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 192.0,
                              child: GeneratedRectangle3Widget1(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 24.0,
                              child: GeneratedFrame1Widget1(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 32.0,
                              width: 343.0,
                              height: 70.0,
                              child: TransformHelper.translate(
                                  x: 1.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedRectangle4Widget1()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 45.0,
                              width: 39.0,
                              height: 39.0,
                              child: TransformHelper.translate(
                                  x: -131.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedRectangle20Widget13()),
                            ),
                            Positioned(
                              left: 312.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 25.0,
                              child: GeneratedNotificationWidget1(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 60.0,
                              width: 71.0,
                              height: 64.0,
                              child: TransformHelper.translate(
                                  x: 2.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse11Widget2()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 65.0,
                              width: 65.0,
                              height: 64.0,
                              child: TransformHelper.translate(
                                  x: 2.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse12Widget2()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 55.99793243408203,
                              width: 22.0,
                              height: 22.00206756591797,
                              child: TransformHelper.translate(
                                  x: -131.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedCombinedShapeWidget3()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 79.71428680419922,
                              width: 34.28571319580078,
                              height: 34.28571319580078,
                              child: TransformHelper.translate(
                                  x: 2.64,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedGroup34Widget1()),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 22.0,
                              child: GeneratedSearchWidget1(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 156.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse10Widget1()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 140.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse11Widget3()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 124.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse12Widget3()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 49.0,
                              width: 32.0,
                              height: 32.0,
                              child: TransformHelper.translate(
                                  x: -67.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedUser1Widget1()),
                            ),
                            Positioned(
                              left: 187.91299438476562,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 26.0,
                              child: GeneratedVector6Widget1(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 10.0,
                              width: 134.0,
                              height: 5.0,
                              child: TransformHelper.translate(
                                  x: 0.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedHomeIndicatorWidget2()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 48.0,
                              width: 30.0,
                              height: 30.0,
                              child: TransformHelper.translate(
                                  x: 73.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedWpffaqWidget1()),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.152;

                                final double height = constraints.maxHeight *
                                    0.012313137997637738;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.25066666666666665,
                                      y: constraints.maxHeight *
                                          0.10424711416055868,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedAlina01Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.08533333333333333;

                                final double height = constraints.maxHeight *
                                    0.011156074293367155;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.248,
                                      y: constraints.maxHeight *
                                          0.11389961871472033,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth * 0.2;

                                final double height = constraints.maxHeight *
                                    0.009095634732927595;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.25066666666666665,
                                      y: constraints.maxHeight *
                                          0.12162162445403718,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Generated30Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.112;

                                final double height = constraints.maxHeight *
                                    0.027027025327577697;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.10933333333333334,
                                      y: constraints.maxHeight *
                                          0.10489061376550696,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedUserpicWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9146666666666666;

                                final double height =
                                    constraints.maxHeight * 0.15958816402561063;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.050666666666666665,
                                      y: constraints.maxHeight *
                                          0.11881868131868131,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup112Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9146666666666666;

                                final double height =
                                    constraints.maxHeight * 0.15958816402561063;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.032,
                                      y: constraints.maxHeight *
                                          0.5139837579412775,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup115Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.9146666666666666;

                                final double height =
                                    constraints.maxHeight * 0.15958816402561063;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.032,
                                      y: constraints.maxHeight *
                                          0.690055427970467,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup116Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 429.3603515625,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 295.0,
                              child: GeneratedGroup90Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
