import 'package:flutter/material.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedButtonMessageWidget42.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedAlina01Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedRectangle21Widget11.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/Generated30Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedCOVID19BBCWidget.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedUserpicWidget1.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/Generated892Widget9.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedImageWidget3.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedGroup45Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/Generated1Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedButtonMessageWidget44.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/Generated1997Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedGroup44Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedGroup43Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedRectangle23Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/Generated281Widget9.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedButtonMessageWidget45.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedGroup46Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/Generated195Widget15.dart';
import 'package:flutterapp/meckathonapp/generatedcardwidget/generated/GeneratedGroup47Widget3.dart';

/* Component Card
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 343.0,
      height: 306.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle21Widget11(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9037900874635568;

                final double height =
                    constraints.maxHeight * 0.13071895424836602;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05539358600583091,
                      y: constraints.maxHeight * 0.8006535947712419,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle23Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.1661807580174927;

                final double height =
                    constraints.maxHeight * 0.06209150326797386;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.22740524781341107,
                      y: constraints.maxHeight * 0.049019607843137254,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedAlina01Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.09329446064139942;

                final double height =
                    constraints.maxHeight * 0.05555555555555555;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.22448979591836735,
                      y: constraints.maxHeight * 0.09803921568627451,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.21865889212827988;

                final double height =
                    constraints.maxHeight * 0.0457516339869281;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.22740524781341107,
                      y: constraints.maxHeight * 0.13725490196078433,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated30Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.3236151603498542;

                final double height =
                    constraints.maxHeight * 0.0457516339869281;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.19533527696793002,
                      y: constraints.maxHeight * 0.8464052287581699,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated1Widget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.10204081632653061;

                final double height =
                    constraints.maxHeight * 0.11437908496732026;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.5306122448979592,
                      y: constraints.maxHeight * 0.6601307189542484,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedButtonMessageWidget42(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.10204081632653061;

                final double height =
                    constraints.maxHeight * 0.11437908496732026;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.7638483965014577,
                      y: constraints.maxHeight * 0.6601307189542484,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroup43Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.0890184630457931;

                final double height =
                    constraints.maxHeight * 0.05228758169934641;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.15451895043731778,
                      y: constraints.maxHeight * 0.6993464052287581,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedButtonMessageWidget44(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.0890184630457931;

                final double height =
                    constraints.maxHeight * 0.05228758169934641;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3935860058309038,
                      y: constraints.maxHeight * 0.6993464052287581,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedButtonMessageWidget45(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.0890184630457931;

                final double height =
                    constraints.maxHeight * 0.05228758169934641;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.6326530612244898,
                      y: constraints.maxHeight * 0.696078431372549,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroup44Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.09329446064139942;

                final double height =
                    constraints.maxHeight * 0.05228758169934641;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.8658892128279884,
                      y: constraints.maxHeight * 0.6993464052287581,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroup45Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07871720116618076;

                final double height =
                    constraints.maxHeight * 0.05555555555555555;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.16326530612244897,
                      y: constraints.maxHeight * 0.7058823529411765,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated281Widget9(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.10204081632653061;

                final double height =
                    constraints.maxHeight * 0.11437908496732026;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.052478134110787174,
                      y: constraints.maxHeight * 0.6601307189542484,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroup46Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.0728862973760933;

                final double height =
                    constraints.maxHeight * 0.0392156862745098;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.40816326530612246,
                      y: constraints.maxHeight * 0.7156862745098039,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated195Widget15(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07871720116618076;

                final double height =
                    constraints.maxHeight * 0.05555555555555555;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.641399416909621,
                      y: constraints.maxHeight * 0.7026143790849673,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated1997Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.06997084548104957;

                final double height =
                    constraints.maxHeight * 0.05555555555555555;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.8833819241982507,
                      y: constraints.maxHeight * 0.7058823529411765,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated892Widget9(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.10204081632653061;

                final double height =
                    constraints.maxHeight * 0.11437908496732026;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3935860058309038,
                      y: constraints.maxHeight * 0.7875816993464052,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedGroup47Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8250728862973761;

                final double height =
                    constraints.maxHeight * 0.3333333333333333;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.0728862973760933,
                      y: constraints.maxHeight * 0.2222222222222222,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCOVID19BBCWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.12244897959183673;

                final double height =
                    constraints.maxHeight * 0.13725490196078433;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.0728862973760933,
                      y: constraints.maxHeight * 0.05228758169934641,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedUserpicWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.08746355685131195;

                final double height =
                    constraints.maxHeight * 0.09803921568627451;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.0728862973760933,
                      y: constraints.maxHeight * 0.8202614379084967,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedImageWidget3(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
