import 'package:flutter/material.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedGroup92Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedEllipse11Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedVector6Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedUser1Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedGroup91Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedWpffaqWidget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedGroup93Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedHOMEWidget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedEllipse12Widget1.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedGroup90Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedHomeIndicatorWidget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/meckathonapp/generatedaccueilwidget/generated/GeneratedIPhoneX11ProLightBaseWidget.dart';

/* Frame Accueil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccueilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1554.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1554.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 233, 233, 233),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 36.776119232177734,
                              child: GeneratedIPhoneX11ProLightBaseWidget(),
                            ),
                            Positioned(
                              left: -536.5,
                              top: 395.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 192.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 24.0,
                              child: GeneratedFrame1Widget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 1470.0,
                              child: GeneratedHOMEWidget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 22.0,
                              child: GeneratedSearchWidget(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 1483.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse10Widget(),
                            ),
                            Positioned(
                              left: 324.0,
                              top: 1483.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse11Widget1(),
                            ),
                            Positioned(
                              left: 308.0,
                              top: 1483.0,
                              right: null,
                              bottom: null,
                              width: 8.0,
                              height: 8.0,
                              child: GeneratedEllipse12Widget1(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 1473.0,
                              right: null,
                              bottom: null,
                              width: 32.0,
                              height: 32.0,
                              child: GeneratedUser1Widget(),
                            ),
                            Positioned(
                              left: 187.91299438476562,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 26.0,
                              child: GeneratedVector6Widget(),
                            ),
                            Positioned(
                              left: 121.0,
                              top: 1539.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 5.0,
                              child: GeneratedHomeIndicatorWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 295.0,
                              child: GeneratedGroup90Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 459.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 295.0,
                              child: GeneratedGroup91Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 777.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 295.0,
                              child: GeneratedGroup92Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 1095.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 295.0,
                              child: GeneratedGroup93Widget(),
                            ),
                            Positioned(
                              left: 246.0,
                              top: 1476.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedWpffaqWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
