import 'package:flutter/material.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup104Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup105Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup90Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup107Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedFrame1Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedEllipse11Widget6.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedHomeIndicatorWidget6.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedEllipse12Widget7.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedEllipse10Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedVectorWidget31.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedVector6Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup34Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup103Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedVectorWidget30.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup110Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedCombinedShapeWidget7.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedSearchWidget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedRectangle20Widget25.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup106Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedEllipse11Widget7.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup108Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedIPhoneX11ProLightBaseWidget9.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedNotificationWidget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedVectorWidget29.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedEllipse12Widget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup111Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcandidatswidget3/generated/GeneratedGroup109Widget.dart';

/* Frame Candidats
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCandidatsWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1456.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1456.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 233, 233, 233),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 36.776119232177734,
                              child: GeneratedIPhoneX11ProLightBaseWidget9(),
                            ),
                            Positioned(
                              left: -536.5,
                              top: 395.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 192.0,
                              child: GeneratedRectangle3Widget3(),
                            ),
                            Positioned(
                              left: -19.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 386.0,
                              height: 24.0,
                              child: GeneratedFrame1Widget3(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 32.0,
                              width: 343.0,
                              height: 70.0,
                              child: TransformHelper.translate(
                                  x: 1.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedRectangle4Widget3()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 45.0,
                              width: 39.0,
                              height: 39.0,
                              child: TransformHelper.translate(
                                  x: -131.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedRectangle20Widget25()),
                            ),
                            Positioned(
                              left: 312.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 25.0,
                              child: GeneratedNotificationWidget3(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 60.0,
                              width: 71.0,
                              height: 64.0,
                              child: TransformHelper.translate(
                                  x: 2.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse11Widget6()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 65.0,
                              width: 65.0,
                              height: 64.0,
                              child: TransformHelper.translate(
                                  x: 2.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse12Widget6()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 55.997934341430664,
                              width: 22.0,
                              height: 22.002065658569336,
                              child: TransformHelper.translate(
                                  x: -131.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedCombinedShapeWidget7()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 79.71428680419922,
                              width: 34.28571319580078,
                              height: 34.28571319580078,
                              child: TransformHelper.translate(
                                  x: 2.64,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedGroup34Widget3()),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 22.0,
                              child: GeneratedSearchWidget3(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 156.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse10Widget3()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 140.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse11Widget7()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 124.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse12Widget7()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 65.58547782897949,
                              width: 15.415040016174316,
                              height: 15.414522171020508,
                              child: TransformHelper.translate(
                                  x: -67.73,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedVectorWidget29()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 49.00002861022949,
                              width: 26.69775390625,
                              height: 16.542695999145508,
                              child: TransformHelper.translate(
                                  x: -67.53,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedVectorWidget30()),
                            ),
                            Positioned(
                              left: 187.91299438476562,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 26.0,
                              child: GeneratedVector6Widget3(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 10.0,
                              width: 134.0,
                              height: 5.0,
                              child: TransformHelper.translate(
                                  x: 0.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedHomeIndicatorWidget6()),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup90Widget3(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 367.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup104Widget(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup106Widget(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 819.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup108Widget(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 1045.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup110Widget(),
                            ),
                            Positioned(
                              left: 195.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup103Widget(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 367.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup105Widget(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup107Widget(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 819.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup109Widget(),
                            ),
                            Positioned(
                              left: 194.0,
                              top: 1045.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 202.0,
                              child: GeneratedGroup111Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 48.0,
                              width: 30.0,
                              height: 30.0,
                              child: TransformHelper.translate(
                                  x: 73.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedVectorWidget31()),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
