import 'package:flutter/material.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedEllipse11Widget5.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup95Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedEllipse12Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedNotificationWidget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedSearchWidget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup34Widget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedEllipse10Widget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedHomeIndicatorWidget4.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedArrow5Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedFrame1Widget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup98Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup100Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedArrow6Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedArrow1Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup96Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedEllipse11Widget4.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup94Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup101Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedVectorWidget11.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup102Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedArrow4Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedRectangle20Widget23.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedEllipse12Widget4.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedArrow3Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedArrow2Widget.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedIPhoneX11ProLightBaseWidget6.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedVector6Widget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedCombinedShapeWidget5.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedVectorWidget14.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedGroup90Widget2.dart';
import 'package:flutterapp/meckathonapp/generatedcalendrierwidget2/generated/GeneratedVectorWidget12.dart';

/* Frame Calendrier
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendrierWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1456.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 375.0,
                      height: 1456.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 233, 233, 233),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 36.776119232177734,
                              child: GeneratedIPhoneX11ProLightBaseWidget6(),
                            ),
                            Positioned(
                              left: -536.5,
                              top: 395.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 192.0,
                              child: GeneratedRectangle3Widget2(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 24.0,
                              child: GeneratedFrame1Widget2(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 32.0,
                              width: 343.0,
                              height: 70.0,
                              child: TransformHelper.translate(
                                  x: 1.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedRectangle4Widget2()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 45.0,
                              width: 39.0,
                              height: 39.0,
                              child: TransformHelper.translate(
                                  x: -131.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedRectangle20Widget23()),
                            ),
                            Positioned(
                              left: 312.0,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 25.0,
                              child: GeneratedNotificationWidget2(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 60.0,
                              width: 71.0,
                              height: 64.0,
                              child: TransformHelper.translate(
                                  x: 2.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse11Widget4()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 65.0,
                              width: 65.0,
                              height: 64.0,
                              child: TransformHelper.translate(
                                  x: 2.00,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse12Widget4()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 55.997934341430664,
                              width: 22.0,
                              height: 22.002065658569336,
                              child: TransformHelper.translate(
                                  x: -131.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedCombinedShapeWidget5()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 79.71428680419922,
                              width: 34.28571319580078,
                              height: 34.28571319580078,
                              child: TransformHelper.translate(
                                  x: 2.64,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedGroup34Widget2()),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 22.0,
                              child: GeneratedSearchWidget2(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 156.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse10Widget2()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 140.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse11Widget5()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 63.0,
                              width: 8.0,
                              height: 8.0,
                              child: TransformHelper.translate(
                                  x: 124.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedEllipse12Widget5()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 65.58547782897949,
                              width: 15.415040016174316,
                              height: 15.414522171020508,
                              child: TransformHelper.translate(
                                  x: -67.73,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedVectorWidget11()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 49.00002861022949,
                              width: 26.69775390625,
                              height: 16.542695999145508,
                              child: TransformHelper.translate(
                                  x: -67.53,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedVectorWidget12()),
                            ),
                            Positioned(
                              left: 187.91299438476562,
                              top: 52.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 26.0,
                              child: GeneratedVector6Widget2(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 10.0,
                              width: 134.0,
                              height: 5.0,
                              child: TransformHelper.translate(
                                  x: 0.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedHomeIndicatorWidget4()),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 243.0,
                              child: GeneratedGroup90Widget2(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: 48.0,
                              width: 30.0,
                              height: 30.0,
                              child: TransformHelper.translate(
                                  x: 73.50,
                                  y: 0.00,
                                  z: 0,
                                  child: GeneratedVectorWidget14()),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 427.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 63.0,
                              child: GeneratedGroup94Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 63.0,
                              child: GeneratedGroup95Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 832.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 63.0,
                              child: GeneratedGroup101Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 1102.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 63.0,
                              child: GeneratedGroup102Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 697.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 63.0,
                              child: GeneratedGroup96Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 967.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 63.0,
                              child: GeneratedGroup98Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 1237.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 63.0,
                              child: GeneratedGroup100Widget(),
                            ),
                            Positioned(
                              left: 323.0,
                              top: 501.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 0.0,
                              child: GeneratedArrow1Widget(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 636.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 0.0,
                              child: GeneratedArrow2Widget(),
                            ),
                            Positioned(
                              left: 324.0,
                              top: 771.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 0.0,
                              child: GeneratedArrow3Widget(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 906.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 0.0,
                              child: GeneratedArrow4Widget(),
                            ),
                            Positioned(
                              left: 324.0,
                              top: 1041.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 0.0,
                              child: GeneratedArrow5Widget(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 1176.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 0.0,
                              child: GeneratedArrow6Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
