import 'package:flutter/material.dart';

/* UndefinedNode PlayButton
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlayButtonWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
